services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sejm_scraper_postgres_data:/var/lib/postgresql/data

volumes:
  sejm_scraper_postgres_data:
