version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sejm_scraper
      POSTGRES_USER: sejm_scraper
      POSTGRES_PASSWORD: sejm_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
